# Generated by Django 5.1.7 on 2025-03-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_options'),
        ('pageTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type_of_personality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pageTest.typesofpersonality', verbose_name='Тип личности'),
            preserve_default=False,
        ),
    ]
