# Generated by Django 5.1.7 on 2025-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес вопроса'),
        ),
    ]
